sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 12
    Sector0:
      start: 0
      end: 32
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 33
      end: 57
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 58
      end: 76
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 77
      end: 143
      scaling: 0.75
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 144
      end: 170
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 171
      end: 205
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 206
      end: 230
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 231
      end: 264
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 265
      end: 290
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector9:
      start: 291
      end: 323
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector10:
      start: 324
      end: 388
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector11:
      start: 389
      end: 419
      scaling: 0.65
      only_FTG: false
      no_FTG: false
