sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 12
    Sector0:
      start: 0
      end: 13
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 14
      end: 34
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 35
      end: 55
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 56
      end: 73
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 74
      end: 140
      scaling: 0.75
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 141
      end: 186
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 187
      end: 236
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 237
      end: 260
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 261
      end: 302
      scaling: 0.67
      only_FTG: false
      no_FTG: false
    Sector9:
      start: 303
      end: 350
      scaling: 0.67
      only_FTG: false
      no_FTG: false
    Sector10:
      start: 351
      end: 380
      scaling: 0.63
      only_FTG: false
      no_FTG: false
    Sector11:
      start: 381
      end: 406
      scaling: 0.6
      only_FTG: false
      no_FTG: false
