sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 11
    Sector0:
      start: 0
      end: 25
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 26
      end: 51
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 52
      end: 69
      scaling: 0.75
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 70
      end: 121
      scaling: 0.75
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 122
      end: 148
      scaling: 0.67
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 149
      end: 177
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 178
      end: 218
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 219
      end: 254
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 255
      end: 299
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector9:
      start: 300
      end: 367
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector10:
      start: 368
      end: 406
      scaling: 0.7
      only_FTG: false
      no_FTG: false
