sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 10
    Sector0:
      start: 0
      end: 37
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 38
      end: 66
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 67
      end: 88
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 89
      end: 151
      scaling: 0.75
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 152
      end: 194
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 195
      end: 233
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 234
      end: 275
      scaling: 0.8
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 276
      end: 316
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 317
      end: 384
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector9:
      start: 385
      end: 420
      scaling: 0.65
      only_FTG: false
      no_FTG: false
