sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 11
    Sector0:
      start: 0
      end: 40
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 41
      end: 74
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 75
      end: 101
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 102
      end: 133
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 134
      end: 160
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 161
      end: 199
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 200
      end: 237
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 238
      end: 259
      scaling: 0.63
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 260
      end: 301
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector9:
      start: 302
      end: 320
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector10:
      start: 321
      end: 403
      scaling: 0.65
      only_FTG: false
      no_FTG: false
