sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 7
    Sector0:
      start: 0
      end: 69
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 70
      end: 196
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 197
      end: 251
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 252
      end: 281
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 282
      end: 333
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 334
      end: 372
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 373
      end: 430
      scaling: 0.55
      only_FTG: false
      no_FTG: false
