sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 9
    Sector0:
      start: 0
      end: 20
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 21
      end: 32
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 33
      end: 47
      scaling: 0.6      
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 48
      end: 71
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 72
      end: 91
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 92
      end: 108
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 109
      end: 129
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 130
      end: 154
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 155
      end: 185
      scaling: 0.65
      only_FTG: false
      no_FTG: false
