sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 12
    Sector0:
      start: 0
      end: 34
      scaling: 0.63
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 35
      end: 65
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 66
      end: 138
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 139
      end: 167
      scaling: 0.63
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 168
      end: 195
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 196
      end: 223
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 224
      end: 240
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 241
      end: 307
      scaling: 0.80
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 308
      end: 342
      scaling: 0.65
      only_FTG: false
      no_FTG: false
    Sector9:
      start: 343
      end: 379
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector10:
      start: 380
      end: 397
      scaling: 0.62
      only_FTG: false
      no_FTG: false
    Sector11:
      start: 398
      end: 418
      scaling: 0.65
      only_FTG: false
      no_FTG: false
