sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 7
    Sector0:
      start: 0
      end: 30
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 31
      end: 55
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 56
      end: 81
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 82
      end: 225
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 226
      end: 277
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 278
      end: 323
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 324
      end: 412
      scaling: 0.2
      only_FTG: false
      no_FTG: false
