sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 8
    Sector0:
      start: 0
      end: 30
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 31
      end: 87
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 88
      end: 212
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 213
      end: 251
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 252
      end: 284
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 285
      end: 331
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 332
      end: 372
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 373
      end: 412
      scaling: 0.55
      only_FTG: false
      no_FTG: false
