sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 7
    Sector0:
      start: 0
      end: 69
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 70
      end: 205
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 206
      end: 245
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 246
      end: 277
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 278
      end: 316
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 317
      end: 357
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 358
      end: 418
      scaling: 0.6
      only_FTG: false
      no_FTG: false
