sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 10
    Sector0:
      start: 0
      end: 51
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 52
      end: 72
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 73
      end: 106
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 107
      end: 130
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 131
      end: 153
      scaling: 0.55
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 154
      end: 185
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 186
      end: 205
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 206
      end: 238
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector8:
      start: 239
      end: 257
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector9:
      start: 258
      end: 298
      scaling: 0.6
      only_FTG: false
      no_FTG: false
